- name: create virtual env
  shell: |
    python3 -m venv {{ VBMC_VENV_DIR }}
    . {{ VBMC_VENV_DIR }}/bin/activate
    pip install --upgrade pip
    pip install -e ./virtualbmc-vbox/
    deactivate
  become: false
  tags: install
