- hosts: 127.0.0.1
  connection: local
  become: true
  max_fail_percentage: 0

  roles:
    - role: vbmc-delete
      tags: always

    - role: vbmcd-stop
      tags: always

    - role: wsl2-subnet-cleanup
      when: "'microsoft-standard' in ansible_kernel"
      tags: wsl2
